### ISSUE TITLE
Add support for MIPS unwinding

### ISSUE THREAD

**Issue by Swatinem** [rust-minidump/rust-minidump#583]
Well, looks like we need to support unwinding of MIPS minidumps.

This is complicated by a few things. MIPS calling conventions define 3 different types of functions it would seem:

* Stackless leaf functions
* Leaf functions with stacks
* Non-leaf functions

Similarly to ARM, MIPS saves the return addr in a register (`$ra`), and only saves it on the stack for non-leaf functions. To make things worse, the DWARF CFI for MIPS does not always have instructions for `ra`. I think this is the case for stackful leaf functions.

Some examples from dwarfdump:

## stackless leaf function:

this doesn’t seem to define anything, so we might as well skip generating anything for it 🤷🏻‍♂️ 

```
000003e8 00000010 000003ec FDE cie=00000000 pc=00016d00...00016d02
  Format:       DWARF32
  DW_CFA_nop:
  DW_CFA_nop:
  DW_CFA_nop:

  0x16d00: CFA=SP_64
```

## leaf function with stack:

it has no instructions on how to restore `$ra`, thats why I think its a leaf function. It returns to `$ra`.

```
000004d4 0000001c 000004d8 FDE cie=00000000 pc=00016de8...00016e6c
  Format:       DWARF32
  DW_CFA_advance_loc: 10
  DW_CFA_def_cfa_offset: +16
  DW_CFA_offset: S1_64 -4
  DW_CFA_offset: S0_64 -8
  DW_CFA_advance_loc1: 116
  DW_CFA_restore: S0_64
  DW_CFA_restore: S1_64
  DW_CFA_def_cfa_offset: +0
  DW_CFA_nop:
  DW_CFA_nop:

  0x16de8: CFA=SP_64
  0x16df2: CFA=SP_64+16: S0_64=[CFA-8], S1_64=[CFA-4]
  0x16e66: CFA=SP_64
```

## non-leaf function

this function restores `$ra` from the stack and would jump to that addr.

```
00000514 00000018 00000518 FDE cie=00000000 pc=00015b94...00015bba
  Format:       DWARF32
  DW_CFA_advance_loc: 22
  DW_CFA_def_cfa_offset: +32
  DW_CFA_offset: RA_64 -4
  DW_CFA_advance_loc: 12
  DW_CFA_restore: RA_64
  DW_CFA_def_cfa_offset: +0
  DW_CFA_nop:
  DW_CFA_nop:

  0x15b94: CFA=SP_64
  0x15baa: CFA=SP_64+32: RA_64=[CFA-4]
  0x15bb6: CFA=SP_64
```
